### ISSUE TITLE
Support for enums

### ISSUE THREAD

**Issue by pmlodawski** [lpsmith/postgresql-simple#110]
Does this library supports enums? 

For example if I define 

```
create type foo_bar as enum ('Foo', 'Bar');
```

How can I use it in queries?
If not, is it possible to add it to this library?

**Comment by michaelpeternell** [comment]
@pmlodawski : were you successful?

I just tried to follow the instructions, but I cannot find a way to call the `typename` function. The `typename` function has `IO` in its signature and it requires a reference to the connection object. Both is unavailable from within a FromField instance. @lpsmith : Am I missing something?

I did manage to write a `FromField` instance, but it's not type-checked at all.

**Comment by phadej** [comment]
@michaelpeternell 

I use something like:

```haskell
{-# LANGUAGE OverloadedStrings #-}

myEnumPGFromField :: PG.FieldParser MyEnum
myEnumPGFromField f mdata = do
    n <- PG.typename f
    if n /= "myenum"
    then PG.returnError PG.Incompatible f ""
    else case mdata of
        Nothing -> PG.returnError PG.UnexpectedNull f ""
        Just bs -> case parseMyEnum bs of
            Nothing -> PG.returnError PG.ConversionFailed f (show bs)
            Just x  -> return x

parseMyEnum :: BS.ByteString -> Maybe MyEnum
parseMyEnum bs = ...
```

Maybe that should be wrapped into a helper, as it only cares about enum name and how to parse the contents.

---

Note that this package is now maintained at https://github.com/phadej/postgresql-simple

**Comment by michaelpeternell** [comment]
@phadej : Thanks :) that's much easier than I expected.
