### ISSUE TITLE
add support for aggregate functions

### ISSUE THREAD

**Issue by levinotik** [lpsmith/postgresql-simple#148]
Wondering if there's a sensible way to add support for aggregate functions so that certain queries could return a single result instead of `[r]`. (Perhaps it would need to be `Maybe r`?)

**Comment by levinotik** [comment]
I'm still pretty new to Haskell...maybe this is best handled by just using `listToMaybe` and doesn't need to be in the library?

**Comment by sopvop** [comment]
Aggregate functions still return you rows. If you expect a single row or nothing, then just use something like
~~~~.haskell
headMay :: [a] -> Maybe a
headMay [] = Nothing
headMay (x:_) = Just x

note :: e -> Maybe a -> Either e a
note e = maybe (Left e) Right

maybeQuery = fmap headMay $ query_ "select * from some_table where primary_key = 1;"

eitherQuery = note "Empty result set, impossible!!" . headMay <$> query_ "select count(*) from some_table"
~~~~

`headMay` and `note` with many other handy combinators are in`errors` package.

**Comment by levinotik** [comment]
@sopvop thanks a lot, really appreciate it

**Comment by cimmanon** [comment]
@sopvop listToMaybe already does that, no need to roll your own.

```haskell
singleItem :: FromRow r => IO (Maybe r)
singleItem = listToMaybe <$> query_ "select * from some_table where primary_key = 1;"
```

A [maybeToEither](http://hackage.haskell.org/packages/archive/MissingH/latest/doc/html/Data-Either-Utils.html#v:maybeToEither) function already exists as well.

**Comment by sopvop** [comment]
I just like names in errors package :-)
