### ISSUE TITLE
dynamic table, columns names and other dynamic SQL

### ISSUE THREAD

**Issue by deem0n** [lpsmith/postgresql-simple#167]
Hello,
I understand the intent about stopping SQL Injections. But what about things like
`LISTEN channel_name;` or `SET search_path = public, other_schema;`?

Is it possible to write
`execute con "LISTEN ?" ("myChannelName" :: SOMETHING )` and get SQL like this: `LISTEN "myChannelName"`

i.e. channel name will be quoted in double quotes in resulting SQL

Thanks

**Comment by lpsmith** [comment]
Yes, you can use the [`Identifier`](https://hackage.haskell.org/package/postgresql-simple-0.5.0.1/docs/Database-PostgreSQL-Simple-Types.html#t:Identifier) or [`QualifiedIdentifier`](https://hackage.haskell.org/package/postgresql-simple-0.5.0.1/docs/Database-PostgreSQL-Simple-Types.html#t:QualifiedIdentifier) types.

I don't know exactly what the search path syntax is off the top of my head;  I would _guess_ that the Identifier syntax would be the correct one.   You can always construct queries yourself,  a [`Query`](https://hackage.haskell.org/package/postgresql-simple-0.5.0.1/docs/Database-PostgreSQL-Simple-Types.html#t:Query) is just newtype wrapper around bytestring.   So you can ultimately construct any query you want,  it's just a decision inherited from `mysql-simple` to discourage writing trivially insecure code.   (One that's not quite as meaningful as when mysql-simple was originally made,  as Monoid is a more prominent typeclass now,  and `<>` has been added as a convenient synonym for mappend.)

**Comment by deem0n** [comment]
Thanks, `Identifier` did the trick. Actually, PostgreSQL has functional alternatives for many SQL commands.
For example, `NOTIFY a, 'b';` can be called with `select pg_notify('a','b')`.
`SET search_path=a,b;` can be called with `SELECT set_config('search_path','a,b', true);`
So you may use Strings and single quotes. But there is no function for LISTEN, so you must use double quoting with `Identifier`.

Also, dealing with Text, ByteString, [Char], String etc is quite frustrating for a haskell newbie like me.
Anyway, here is my working code:
```haskell
import System.IO
import Database.PostgreSQL.Simple
import Database.PostgreSQL.Simple.Notification
import Database.PostgreSQL.Simple.Types --Identifier
import Data.String
import Control.Monad
import Data.ByteString (ByteString)

runLoggerLoop :: Connection -> String -> IO ()
runLoggerLoop con ch = listen >> loop
  where
    listen = execute con "LISTEN ?" [Identifier (fromString ch)]
    loop = forever $
      getNotification con >>= processAuditMessage' . notificationData
```

**Comment by lpsmith** [comment]
Glad I could help.  Two quick comments:

~~~
import Database.PostgreSQL.Simple.Types --Identifier
~~~

You could write this import as:

~~~
import Database.PostgreSQL.Simple.Types(Identifier(Identifier))
~~~

The first imports the type constructor, the second imports the data constructor.   You can use wild cards on the data constructor and write `Identifer(..)` instead.

Also, one issue with notifications is that they can be lost if your logger is disconnected or not running when they are sent out.   If you need reliable delivery,  you'll need to write the data to a table,  and then send a notification for your logger to wake up and process the new stuff in the table.   In this case your logger would look something like this:

1.  connect to the database
2.  subscribe to relevant notification channels
3.  check tables for unprocessed data,  and process it
4.  wait for a notification
5.  go to 3

**Comment by deem0n** [comment]
Thanks for hints!
