### ISSUE TITLE
debugging sql output

### ISSUE THREAD

**Issue by charles-cooper** [lpsmith/postgresql-simple#175]
Is there any way to debug SQL output? For example a function to generically print the SQL response as a formatted table.

**Comment by lpsmith** [comment]
You are on your own on this one;  however I will mention that column names are available via the `FromField` interface.   On occasion, I've found the following definitions useful:

~~~
data Attribute a = Attribute ByteString a

instance FromField a => FromField (Attribute a) where
    fromField f mv = Attribute (fromMaybe "" (name f)) <$> fromField f mv

newtype Raw = Raw (Maybe ByteString)

instance FromField Raw where
    fromField _f mv = pure (Raw mv)
~~~
