### ISSUE TITLE
Allow failing a RowParser

### ISSUE THREAD

**Issue by ivan-m** [lpsmith/postgresql-simple#178]
I have a query that's returning data into a custom format (which has an instance of `FromRow`).  The problem is, the data in the DB has some quality issues and thus one of the attempted type conversions (specifically creating a `ZonedTimestamp` value) doesn't always succeed.

This means that if just one row has a problematic value, the entire query fails to parse.

I tried to handle this by using `queryWith (optional fromRow)` hoping to get `[Maybe MyType]` out, and then I could filter out the `Nothing` values to get solely the values that successfully parsed, but this gives me back an error of a different type (from being about the type being wrong, to "mismatch between number of columns to convert and number in target type").

**Comment by lpsmith** [comment]
FromRow has an Alternative instance,  as does FromField.

**Comment by ivan-m** [comment]
That's what I used when trying to do `queryWith (optional fromRow)`; it led to a different error.

I can provide more details when I get back into work on Monday.

**Comment by lpsmith** [comment]
Ahh, I forgot what `optional` meant.  Yes, that does seem slightly curious that it doesn't work...

**Comment by ivan-m** [comment]
So, some more details as promised:

The datatype we're using is:
```haskell
data FactRow = FactRow
    { _fact_source      :: Text
    , _projection_field :: Text
    , _value            :: Value -- JSON blob
    , _policy           :: Text
    , _priority         :: Int
    , _observed_at      :: ZonedTimestamp
    }
    deriving (Show, Read)

instance FromRow FactRow where
    fromRow =
        FactRow <$> field
                <*> field
                <*> field
                <*> field
                <*> field
                <*> field
```

We also has a query that will return the six required values in that order... but some of the data that we're accessing has malformed timestamps (they appear as something like `0006-12-08 17:00:00+10:04:52`, seemingly with the timezone embedded in and a very strange year).  What I would prefer to do is just skip the rows that have such values.

**Comment by lpsmith** [comment]
Ok,  `optional` should theoretically work in this case,  so what error are you getting when you try to use that?

Also,  are you aware of what `timestamp with time zone` and `timestamp without time zone` actually mean in the context of postgresql?   In particular,  there's a big difference between time zones and  offsets,  and neither the time zone nor the offset is stored as part of the underlying `timestamp with time zone value`,  but rather computed on the fly based on the `timezone` GUC variable.  

 You might want to read the documentation in the [Time](https://hackage.haskell.org/package/postgresql-simple-0.5.1.2/docs/Database-PostgreSQL-Simple-Time.html) module;  it still needs a bit of work,  but it's a starting point.

**Comment by ivan-m** [comment]
When not using `optional` I get this error:
```haskell
λ> query conn myQuery myParams
*** Exception: ConversionFailed {errSQLType = "timestamptz", errSQLTableOid = Just (Oid 205450), errSQLField = "observed_at", errHaskellType = "ZonedTimestamp", errMessage = "endOfInput"}
```
Using `optional` (so the result should now be `IO [Maybe FactRow]`):
```haskell
λ> queryWith (optional fromRow) conn myQuery myParams
*** Exception: ConversionFailed {errSQLType = "6 values: [(Basic {typoid = Oid 25, typcategory = 'S', typdelim = ',', typname = \"text\"},Just \"opus_property\"),(Basic {typoid = Oid 25, typcategory = 'S', typdelim = ',', typname = \"text\"},Just \"roof_type\"),(Basic {typoid = Oid 114, typcategory = 'U', typdelim = ',', typname = \"json\"},Just \"\\\"CT\\\"\"),(Basic {typoid = Oid 25, typcategory = 'S', typdelim = ',', typname = \"text\"},Just \"priority_t[...]\"),(Basic {typoid = Oid 23, typcategory = 'N', typdelim = ',', typname = \"int4\"},Just \"110\"),(Basic {typoid = Oid 1184, typcategory = 'D', typdelim = ',', typname = \"timestamptz\"},Just \"0006-01-27[...]\")]", errSQLTableOid = Nothing, errSQLField = "", errHaskellType = "0 slots in target type", errMessage = "mismatch between number of columns to convert and number in target type"}
```
(Regarding timestamps: we're using it more to get the date out of the value so we know when it was imported.  The data is all from local databases with "date entered" values.  We don't actually need to know these values apart from using them to determine if one is newer/older.  As such the distinction between zoned and unzoned isn't that important.  We also fully expect to have a lot of really weird values in that column as the source databases we've copied into our system don't always have clean/sensible values, so it would be nice to just skip rows that are unparseable.)

**Comment by lpsmith** [comment]
Ahh, my apologies to not responding to this earlier.

I forgot you have to provide something that consumes all the fields.   There's several ways you could do this,  the most efficient would be to get into the internals of the row parser and set the current column to the number of columns.

I wonder if this violates any of the `Alternative` laws that are widely recognized... ugh.

**Comment by lpsmith** [comment]
Ok, I don't think this violates any Alternative laws,  which AFAICT,  just say that `Alternative` forms a monoid,  and doesn't relate `<|>` with `<*>` or `<$>`.   Not to mention, that the alternative instance comes directly from `transformers`,  though it's the running function that's ultimately causing some seemingly counter intuitive behavior here. 

Now,  there are two ways I can think of to munch the row:   write a field parser that just returns some sort of unit and ignores everything,  then use the list row parser,  or access the newtype constructor that defines `RowParser` via `Database.PostgreSQL.Simple.Internal` and set the `PQ.Column` to the last column.

**Comment by ivan-m** [comment]
There don't seem to be any documented Alternative laws, but my understanding of `a <|> b` is that it's meant to return `b` when `a` fails.

It looks like the problem falls down to the [`Alternative` instance for `Conversion`](https://github.com/lpsmith/postgresql-simple/blob/master/src/Database/PostgreSQL/Simple/Internal.hs#L476): IIUC, it looks like if you have an error case then you're re-running `<|>` when it should be ignoring it (since it had an error).

**Comment by lpsmith** [comment]
That's not re-running anything;  what that's doing is collecting the errors if both sides of the alternative fails,  see the [Ok](https://hackage.haskell.org/package/postgresql-simple-0.5.1.2/docs/Database-PostgreSQL-Simple-Ok.html) module.

The issue is basically as if you wrote `optional someParser <* endOfInput` in Aeson:  the optional returns `Nothing`, but the `endOfInput` fails.

**Comment by ivan-m** [comment]
Oh, right, so the definition is equivalent to:
```haskell
ma <|> mb = Conversion $ \ conn -> liftA2 (<|>) (runConversion ma conn) (runConversion mb conn)
```
(without relying upon the laziness in the definition of `<|>` for `Ok`).

I suppose I'm used to other parsing libraries were `<|>` is used for backtracking (either with or without a `try` combinator) and that `optional` would return `Nothing` if something is unparseable.  Though when I tried to find any laws stating this behaviour there weren't any (nor even for `MonadPlus`): the closest is that `MonadPlus` types ["support choice and failure"](https://hackage.haskell.org/package/base-4.8.2.0/docs/Control-Monad.html#t:MonadPlus).

**Comment by lpsmith** [comment]
```haskell
ma <|> mb = Conversion $ \ conn -> liftA2 (<|>) (runConversion ma conn) (runConversion mb conn)
```

Not quite the same;  with this definition I think that any effects that the `mb` has (and arbitrary IO is admitted during conversions,  but is also strongly discouraged;  mostly it is used for querying the TypeInfo cache and possibly populating the TypeInfo cache by querying the `pg_type` table.) happen whether or not the `ma` returns an `Ok` or returns `Errors`.    Whereas with the actual source version,  the effects only happen if the first guy fails.

So conceptually yes,  they are equivalent,  but only because the IO effects are expected to be referentially transparent.   (And indeed,  they should be,  unless somebody is manipulating the postgresql types your client program is using while it is running,  or somebody decides to use [`Internal.liftConversion`](https://hackage.haskell.org/package/postgresql-simple-0.5.1.2/docs/Database-PostgreSQL-Simple-Internal.html#v:liftConversion) to do something not referentially transparent.

But again,  your last paragraph suggests to me that either we are talking past each other,  or you are misunderstanding the issue.   Namely,  `<|>` does indeed work the way you think it works;  it backtracks on a conversion error.   The issue isn't with `<|>`,  this error is due to the fact that when a `RowParser` is run,  postgresql-simple is expecting for everything to be consumed after it runs.   So `optional` causes the failing RowParser to backtrack to the beginning of the row,  immediately succeeds leaving the entire row unconsumed,  then postgresql-simple says,  hey,  you didn't consume everything,  so I'll throw an exception for you.   (Because that's usually what people want,  in context.)

See the source for [`getRowWith`](https://github.com/lpsmith/postgresql-simple/blob/0d78ba3faca0a41e613049fef1a9c35e674bc487/src/Database/PostgreSQL/Simple.hs#L695).

**Comment by ivan-m** [comment]
/me facepalms

I somehow completely forgot that using `optional` would send the parser back to the beginning of the row... I guess for some reason I thought it was acting on a row-by-row basis, so if a single row failed it would just skip over it.

In that case I'll try and do a workaround for this to just skip a row.

Thanks for your help!

**Comment by lpsmith** [comment]
You are welcome :)

The most efficient thing to do would be to import `Internal`,  and use the `RowParser` constructor to create a action that set the `PQ.Column` number that's held in the `StateT` to the last column (see `getRowWith` etc. for the right function calls)

 Then you could define `optionalRow p = (Just <$> p) <|> (munchRow *> pure Nothing)`

**Comment by ivan-m** [comment]
This is what I ended up coming up with, in case anyone is searching for a solution:
```haskell
tryParseRow :: (FromRow r) => RowParser (Maybe r)
tryParseRow = (Just <$> fromRow) <|> skipRow
  where
    skipRow = do currRow <- RP ask
                 ncols <- liftRowParser (nfields (rowresult currRow))
                 RP . lift $ put ncols
                 return Nothing
```

**Comment by lpsmith** [comment]
Hmm, I wonder if it would make sense to change the logic test in `getRowWith to `cols == ncols || cols == 0`

That makes me slightly uncomfortable, as it's an unprincipled heuristic and a obscure behavior, but it would make the regular `optional` work as expected.   It'd also make `queryWith (pure x)` also always succeed,  which is perhaps undesirable,  but I don't think any of the default `FromRow` instances consume zero columns.

**Comment by ivan-m** [comment]
What about `Only ()`?  It appears to consume 0 columns.

But yes, setting `cols == ncols` is an implementation issue, so using that in my own parser is definitely a hack.

**Comment by lpsmith** [comment]
IIRC,  `Only ()` consumes one column,  of the void type.   But I should check that.

At the same time,  I am thinking about revising the interface,  which might make some of these issues moot.   In any case,  I should keep these issues in mind,  so that they might inform the new interface.
