### ISSUE TITLE
CHANGES is not in dist tarball

### ISSUE THREAD

**Issue by charles-cooper** [lpsmith/postgresql-simple#183]
See https://hackage.haskell.org/package/postgresql-simple -- no changelog! I think the appropriate thing to do is add CHANGES to the `extra-source-files` section. Having the changelog in the dist tarball is helpful for example when reviewing stackage diffs: https://www.stackage.org/diff/lts-5.14/lts-5.15.

**Comment by lpsmith** [comment]
Not including the changelog is not an accident, but I'm open to changing that.   It does make the download a wee bit smaller,  and I kinda like the ability to tweak the changelog without uploading a new version.

**Comment by lpsmith** [comment]
Oh, stack doesn't include a link to the repo listed in the .cabal file,  unlike hackage,  so the changelog isn't as "close".   Ugh.

**Comment by lpsmith** [comment]
Yes,  now that I've been experimenting with Stack a little bit,  I can see that leaving the changelog out entirely is less than desirable.

What if I included a CHANGELOG.md that had a link to github?   Or,  perhaps,  a truncated changelog with only a few of the most recent releases,  and a link to the full changelog on github?    I wonder if cabal sdist has a hook for generating that sort of file...

**Comment by charles-cooper** [comment]
Thanks!
