### ISSUE TITLE
`foldM'` and `forM'` contain redundant bangs.

### ISSUE THREAD

**Issue by effectfully** [lpsmith/postgresql-simple#197]
[Here](https://github.com/lpsmith/postgresql-simple/blob/a8f6a901a38df0f65906889bc7f20bf59ecdd73b/src/Database/PostgreSQL/Simple.hs#L647) are the definitions:

```
forM' :: (Ord n, Num n) => n -> n -> (n -> IO a) -> IO [a]
forM' lo hi m = loop hi []
  where
    loop !n !as
      | n < lo = return as
      | otherwise = do
           a <- m n
           loop (n-1) (a:as)
{-# INLINE forM' #-}

foldM' :: (Ord n, Num n) => (a -> n -> IO a) -> a -> n -> n -> IO a
foldM' f a lo hi = loop a lo
  where
    loop a !n
      | n > hi = return a
      | otherwise = do
           a' <- f a n
           loop a' (n+1)
{-# INLINE foldM' #-}
```

There is no need to force `n` in both the functions, because it gets forced in `n > hi`. There is no need to force `as` in `forM'`, because it's already always in WHNF.

**Comment by lpsmith** [comment]
You are correct in that none of those bang patterns are critically important,  but I very much doubt that removing them would result in the same code being generated across many different versions of GHC,  and I would expect that in most cases,  the bangs do result in slightly better code being generated.

But yes,  the emphasis is on _slight_ here.
