### ISSUE TITLE
Statement quote failure (create table)

### ISSUE THREAD

**Issue by rsoeldner** [lpsmith/postgresql-simple#249]
I run into this issue with variable table names:

```
mkTableStmt :: Query
mkTableStmt = [sql| CREATE TABLE ? (hi integer); |]
```

the `formatQuery con mkTableStmt ["Foo"]`

will generate the following:
`"CREATE TABLE 'Foo' ( hi integer);"`

which will fail with ` *** Exception: SqlError {sqlState = "42601", sqlExecStatus = FatalError, sqlErrorMsg = "syntax error at or near \"'Foo'\"", sqlErrorDetail = "", sqlErrorHint = ""}`

The problem is the single quote, which is not allowed in this place, the `"` is allowed. 

Is this intended ?

Cheers

**Comment by lpsmith** [comment]
Hi,  you might want to check out the [`Identifier`](https://hackage.haskell.org/package/postgresql-simple-0.5.3.0/docs/Database-PostgreSQL-Simple-Types.html#t:Identifier) and [`QualifiedIdentifier`](https://hackage.haskell.org/package/postgresql-simple-0.5.3.0/docs/Database-PostgreSQL-Simple-Types.html#t:QualifiedIdentifier) types.
