### ISSUE TITLE
Lose TZ in timestamptz

### ISSUE THREAD

**Issue by YurovRuslan** [lpsmith/postgresql-simple#264]
I have a table which creates like:

```
create_table = [sql|
CREATE TABLE IF NOT EXISTS sometable
    ( ...
    , time TIMESTAMP WITH TIME ZONE NOT NULL
    ...
    );
|]
```

Then I create `someschema` from `sometable`. Field `time` goes via psql functions: `tstzrange`, `MAX` and `time_bucket`(tsdb)

Then I have a query to this table:

```
data <- query conn Sql.selectFromSomeSchema (timeZoneName $ zonedTimeZone from, ...)
```

Sql query looks like:

```
selectFromSomeSchema = [sql|
SELECT          
    timezone(?, LOWER(range))
    , timezone(?, UPPER(range))
    , CAST(EXTRACT(EPOCH FROM (UPPER(range) - LOWER(range))) AS INTEGER) FROM someschema
WHERE
    ...
|]
```

And I have an error:

```
"Incompatible {errSQLType = \"timestamp\", errSQLTableOid = Nothing, errSQLField = \"timezone\", errHaskellType = \"ZonedTime\", errMessage = \"\"}"
```

**Comment by lpsmith** [comment]
Timestamptz does not store the timezone on a per-value or per-column basis.  You should read the documentation I wrote in the [`Time`](https://hackage.haskell.org/package/postgresql-simple-0.5.4.0/docs/Database-PostgreSQL-Simple-Time.html) module.

**Comment by lpsmith** [comment]
Also, you might be interested in reading the discussion of issue #69.
