### ISSUE TITLE
Query resulted in a command response

### ISSUE THREAD

**Issue by linearray** [lpsmith/postgresql-simple#272]
About once a year I hit the error mentioned above and frantically try to fix it. Googling it is of no use, because the only results are from pg-simple's [source code](https://github.com/lpsmith/postgresql-simple/blob/master/src/Database/PostgreSQL/Simple/Internal/PQResultUtils.hs#L42), where I can see that `status` is `PQ.CommandOk`, which does not present me with any obvious clues to the source of the problem.

After I inch closer to my inevitable demise for an hour or so it hits me that I used `query` instead of `execute`, or even more likely I forgot something like `RETURNING id` in a query.

Would you accept a patch that changes the error message to something like "Query resulted in a command response (did you mean to use `execute`?)"

**Comment by phadej** [comment]
I'm not sure what you are talking about, but yes.

/Note/ currently I maintain the `postgresql-simple` at https://github.com/phadej/postgresql-simple

**Comment by jonoabroad** [comment]
This was helpful.

**Comment by saurabhnanda** [comment]
I hit the same error and this was the first result on Google. Thank you :-)
