### ISSUE TITLE
Support inserting into variable number of subset of fields (probably using VALUES)

### ISSUE THREAD

**Issue by robinp** [lpsmith/postgresql-simple#281]
Hello,

It would be nice to support something like

```
execute conn "INSERT INTO tbl (?) VALUES (?)" (ColNames [Identifier "a", ...], Values ...)
```

AFAIU the `ColNames` bit which I made up is missing, while there's already a `Values` wrapper. No idea though.

**Comment by cimmanon** [comment]
This package was handed off to another maintainer.  Try https://github.com/haskellari/postgresql-simple/

**Comment by robinp** [comment]
Thanks, and sorry for the mistake! Would be nice to archive the repo and/or show the link in the README file, so people are more aware.

**Comment by robinp** [comment]
Closing
