### ISSUE TITLE
Working with ranges

### ISSUE THREAD

**Issue by nmk** [lpsmith/postgresql-simple#75]
Does postgresql-simple support working with ranges?

In particular, I am interested in using `daterange` columns but cannot figure out what the representing types should be. An example would be most helpful.

Thanks a lot in advance!

**Comment by lpsmith** [comment]
Ok,  there will be some kind of support for Ranges in postgresql-simple 0.5,  see 300410ab4fa7ba0dce22bbdcd6ebcdf7702347f9 and #125.
